steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/RanjithKuraya/TEMCICD.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}', 'TEMCICD']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west3-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag','gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}', 'europe-west3-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}' ] 


#- name: 'gcr.io/cloud-builders/kubectl'
#  args: [
#    'set',
#    'image',
#    'deployment',
#    'cicd-deploy',
#    'gke-image-sha256-1=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}'
#    ]
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'
       # Or use NONE if you don't want any logging.
options:
  logging: 'CLOUD_LOGGING_ONLY'  # Choose your desired logging behavior
 
substitutions:
  _IMAGE_NAME: tem-image
  _SHORT_SHA: v1
  _PROJECT_ID: glb-fs-wgh-app-dev

